# Using arch as a base, because of package selection
FROM ghcr.io/ublue-os/arch-toolbox:latest@sha256:411b89faf36ba311dbceaba21bb43fdc2ed329db9acada76e164a570fa2bf38f AS base
ARG GPU_VENDOR=amd

COPY ./files /

RUN case "${GPU_VENDOR}" in \
        nvidia) \
            GPU_PKGS="nvidia-utils lib32-nvidia-utils egl-wayland libva-nvidia-driver" ;; \
        intel) \
            GPU_PKGS="vulkan-intel lib32-vulkan-intel intel-media-driver vulkan-mesa-layers lib32-vulkan-mesa-layers" ;; \
        *) \
            GPU_PKGS="vulkan-radeon lib32-vulkan-radeon libva-mesa-driver vulkan-mesa-layers lib32-vulkan-mesa-layers" ;; \
    esac && \
    pacman -Syu \
        ${GPU_PKGS} \
        vulkan-tools \
        lib32-libnm \
        openal \
        pipewire \
        pipewire-pulse \
        pipewire-alsa \
        pipewire-jack \
        wireplumber \
        lib32-pipewire \
        lib32-pipewire-jack \
        lib32-libpulse \
        lib32-openal \
        nano \
        yad \
        xdg-user-dirs \
        xdotool \
        xorg-xwininfo \
        wmctrl \
        wxwidgets-gtk3 \
        libbsd \
        noto-fonts-cjk \
        glibc-locales \
        jdk21-openjdk \
        fastfetch \
        --noconfirm && \
    # Installed separately, so they use dependencies from above
    pacman -S \
        steam \
        lutris \
        prismlauncher \
        mangohud \
        lib32-mangohud \
        goverlay \
        gamescope \
        --noconfirm && \
        wget https://raw.githubusercontent.com/Shringe/LatencyFleX-Installer/main/install.sh -O /usr/bin/latencyflex && \
        sed -i 's@"dxvk.conf"@"/usr/share/latencyflex/dxvk.conf"@g' /usr/bin/latencyflex && \
        chmod +x /usr/bin/latencyflex && \
    pacman -S --clean --clean && \
    rm -rf /var/cache/pacman/pkg/*

RUN useradd -m --shell=/bin/bash aur && usermod -L aur && \
    echo "aur ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# AUR can't run as root
USER aur
WORKDIR /home/aur
RUN paru -S \
        aur/protontricks \
        aur/lib32-gperftools \
        aur/steamcmd \
        aur/protonup-qt \
        aur/heroic-games-launcher-bin \
        aur/mcaselector \
        aur/greenlight-bin \
        aur/obs-vkcapture \
        lib32-obs-vkcapture \
        --noconfirm
USER root
WORKDIR /

ADD https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar \
    /opt/PrismLauncher/instances/create-just-for-fun/packwiz-installer-bootstrap.jar

RUN chmod +x /usr/local/bin/prism-instance-bootstrap.sh

# I'm the owner of the copyright, LOL
ADD https://raw.githubusercontent.com/First-Non-Interesting-Username/create-just-for-fun/main/artworks/logo.png \
    /opt/PrismLauncher/icons/create-just-for-fun-logo.png

# The files added in the ADD steps above should be usable by everyone
RUN chmod -R a+rX /opt/PrismLauncher


RUN sed -i 's@ (Runtime)@@g' /usr/share/applications/steam.desktop && \
    sed -i 's/-march=x86-64 -mtune=generic/-march=native -mtune=native/g' /etc/makepkg.conf && \
    userdel -r aur && \
    rm -drf /home/aur && \
    sed -i '/aur ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers && \
    sed -i '/root ALL=(ALL) NOPASSWD: ALL/d' /etc/sudoers && \
    rm -rf \
        /home/aur/.cache/* \
        /tmp/* \
        /var/cache/pacman/pkg/*

ENV STEAM_NO_CEF_SANDBOX=1

# Create Plasma and GNOME images, differing by type of XDG portal
FROM base AS plasma

RUN sed -i 's/-march=native -mtune=native/-march=x86-64 -mtune=generic/g' /etc/makepkg.conf && \
    pacman -S \
        xdg-desktop-portal-kde \
        --noconfirm && \
    rm -rf /var/cache/pacman/pkg/*

RUN sed -i 's/-march=x86-64 -mtune=generic/-march=native -mtune=native/g' /etc/makepkg.conf && \
    rm -rf \
        /tmp/*

FROM base AS gnome

RUN sed -i 's/-march=native -mtune=native/-march=x86-64 -mtune=generic/g' /etc/makepkg.conf && \
    pacman -S \
        xdg-desktop-portal-gtk \
        xdg-desktop-portal-gnome \
        --noconfirm && \
    rm -rf /var/cache/pacman/pkg/*

RUN sed -i 's/-march=x86-64 -mtune=generic/-march=native -mtune=native/g' /etc/makepkg.conf && \
    rm -rf \
        /tmp/*

# Storage and network optimization, rechunking the image        
FROM quay.io/coreos/chunkah:latest@sha256:8b56578258d1d10d3e1c7b0f71a4d05317c5fde331c4f483576a1b60e65f0cea AS chunkah-plasma
ARG SOURCE_DATE_EPOCH
ARG IMAGE_NAME=gbox-plasma-amd
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
RUN --mount=type=bind,target=/run/src,rw \
    --mount=from=plasma,target=/chunkah,ro \
    chunkah build \
    --skip-special-files \
    --max-layers 64 \
    --label=name=${IMAGE_NAME} \
    --output oci:/run/src/out-plasma
FROM oci:out-plasma AS gbox-plasma
RUN --mount=type=bind,from=chunkah-plasma,target=/tmp/chunkah-dependency true

FROM quay.io/coreos/chunkah:latest@sha256:8b56578258d1d10d3e1c7b0f71a4d05317c5fde331c4f483576a1b60e65f0cea AS chunkah-gnome
ARG SOURCE_DATE_EPOCH
ARG IMAGE_NAME=gbox-gnome-amd
ENV SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}
RUN --mount=type=bind,target=/run/src,rw \
    --mount=from=gnome,target=/chunkah,ro \
    chunkah build \
    --skip-special-files \
    --max-layers 64 \
    --label=name=${IMAGE_NAME} \
    --output oci:/run/src/out-gnome
FROM oci:out-gnome AS gbox-gnome
RUN --mount=type=bind,from=chunkah-gnome,target=/tmp/chunkah-dependency true
